before_install:
    - sudo apt-get install npm
install:
    - npm install -g grunt grunt-cli
    - npm install
script:
    - mkdir _build
    - cd _build
    - cmake ..
    - ctest -VV -S ../cmake/travis-ci.cmake
